CREATE TABLE clients (
    id SERIAL PRIMARY KEY,
    instagram_username VARCHAR UNIQUE NOT NULL,
    access_token VARCHAR NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE posts_to_monitor (
    id SERIAL PRIMARY KEY,
    client_id INTEGER REFERENCES clients(id),
    post_id VARCHAR NOT NULL,
    keyword VARCHAR NOT NULL,
    predefined_message VARCHAR NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sent_dms (
    id SERIAL PRIMARY KEY,
    comment_id VARCHAR UNIQUE NOT NULL,
    client_id INTEGER REFERENCES clients(id),
    sent_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
